const QUEUE_INFO = {
  ASYNC_EMAIL_QUEUE: {
    NAME: "SHOP-HERE-EMAIL-QUEUE",
    LIMIT: 5,
  },
  GENARAL_QUEUE: {
    NAME: "SHOP-HERE-GENERAL-QUEUE",
    LIMIT: 5,
  },
  SMS_QUEUE: {
    NAME: "SHOP-HERE-SMS-QUEUE",
    LIMIT: 5,
  },
  NOTIFICATION_QUEUE: {
    NAME: "SHOP-HERE-NOTIFICATION-QUEUE",
    LIMIT: 5,
  },
};

module.exports = {
  QUEUE_INFO,
};
